### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by irabro1992** [TAJLNsScripts/iq.com-downloader#1]
hi , thanks for your script . sometime it works. but sometimes , it just happen like this..
any idea ?

Initializing selenium
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Message: unknown error: cannot connect to chrome at 127.0.0.1:63109
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0093A813+48355]
        (No symbol) [0x008CC4B1]
        (No symbol) [0x007D5220]
        (No symbol) [0x007CB355]
        (No symbol) [0x007F5C68]
        (No symbol) [0x007F06B4]
        (No symbol) [0x007F0491]
        (No symbol) [0x00820C55]
        (No symbol) [0x0082093C]
        (No symbol) [0x0081A536]
        (No symbol) [0x007F82DC]
        (No symbol) [0x007F93DD]

**Comment by TAJLNsScripts** [comment]
This happens sometimes if the script doesn't exit properly for any reason, the chrome stays running in the background. To fix it, you can close all chrome instances with "taskkill /F /IM "chrome.exe" /T" on windows. I'm sure there is a similar command for linux

**Comment by irabro1992** [comment]
> taskkill /F /IM "chrome.exe" /T

thanks for your help. let me ask you something again.
it keep happening when you tried to make bulk download or single download for
480p and 360p .............

Choose resolution: 4
No dash request
Detected series
Do you want to download the entire series? (y/n): n
Single episode download selected
Extracting m3u8 from dash response
Failed to extract dash response from url, please try again
Failed dash extract

**Comment by irabro1992** [comment]
new error happen again like this.....


Initializing selenium
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
[WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail

Bye :)
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\My Data\iq.com-downloader-main\iq.py", line 24, in myexcepthook
    s_exit()
  File "D:\My Data\iq.com-downloader-main\iq.py", line 36, in s_exit
    driver.quit()
NameError: name 'driver' is not defined

Original exception was:
Traceback (most recent call last):
  File "D:\My Data\iq.com-downloader-main\iq.py", line 285, in <module>
    driver = selenium_init()
  File "D:\My Data\iq.com-downloader-main\iq.py", line 64, in selenium_init
    driver = uc.Chrome(options=options)
  File "C:\Users\cmvps1\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\cmvps1\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    browser = subprocess.Popen(
  File "C:\Users\cmvps1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\cmvps1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail

**Comment by TAJLNsScripts** [comment]
Tried it on this title: https://www.iq.com/play/mysterious-lotus-casebook-episode-1-2f3498mliw0?lang=en_us and it works for me, on what title did you try this on?

**Comment by irabro1992** [comment]
> Tried it on this title: https://www.iq.com/play/mysterious-lotus-casebook-episode-1-2f3498mliw0?lang=en_us and it works for me, on what title did you try this on?

same title with you. it works for 1080p . when i tried to download the whole series with 480p and 360p ,
it just happen like the previous error . mostly

**Comment by TAJLNsScripts** [comment]
Their player may act unpredictable some times, if its not working for you and you really want to download in those qualities, comment out headless in selenium_init, start the script, visit any video, set quality and watch for a little bit so it will remember it for the next time, then uncomment headless and rerun the script and use it normally. Should work that way

**Comment by irabro1992** [comment]
yeah. it works now. do u have any plan to support for iqiyi.com. if you support , we can download with it 4K resolution.

**Comment by TAJLNsScripts** [comment]
That would require remaking most of the script and I'm currently not interested in that

**Comment by irabro1992** [comment]
Thanks for your answer. However , i am already greatful for the scripts which you released recently.
Thank you.
